title: PaveTheChange.org
description: Resources, documentation, and deep-dive thinking behind PaveTheChange.org

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

logo: "/assets/images/logo.png"
